export const ACCOUNT_VALIDATION_REQUEST = 'ACCOUNT_VALIDATION_REQUEST';
export const ACCOUNT_VALIDATION_SUCCESS = 'ACCOUNT_VALIDATION_SUCCESS';
export const ACCOUNT_VALIDATION_FAILURE = 'ACCOUNT_VALIDATION_FAILURE';