export const AUTHORIZE_COMMISSION_REQUEST = 'AUTHORIZE_COMMISSION_REQUEST';
export const AUTHORIZE_COMMISSION_SUCCESS = 'AUTHORIZE_COMMISSION_SUCCESS';
export const AUTHORIZE_COMMISSION_FAILURE = 'AUTHORIZE_COMMISSION_FAILURE';