export const AUTHORIZE_TRANSACTIONS_REQUEST = 'AUTHORIZE_TRANSACTIONS_REQUEST';
export const AUTHORIZE_TRANSACTIONS_SUCCESS = 'AUTHORIZE_TRANSACTIONS_SUCCESS';
export const AUTHORIZE_TRANSACTIONS_FAILURE = 'AUTHORIZE_TRANSACTIONS_FAILURE';