export const CLIENT_VALIDATION_REQUEST = 'CLIENT_VALIDATION_REQUEST';
export const CLIENT_VALIDATION_SUCCESS = 'CLIENT_VALIDATION_SUCCESS';
export const CLIENT_VALIDATION_FAILURE = 'CLIENT_VALIDATION_FAILURE';