export const ELECTRICITY_PAYMENT_REQUEST = 'ELECTRICITY_PAYMENT_REQUEST';
export const ELECTRICITY_PAYMENT_SUCCESS = 'ELECTRICITY_PAYMENT_SUCCESS';
export const ELECTRICITY_PAYMENT_FAILURE = 'ELECTRICITY_PAYMENT_FAILURE';