export const GET_ELECTRICITYDETAILS_REQUEST = 'GET_ELECTRICITYDETAILS_REQUEST';
export const GET_ELECTRICITYDETAILS_SUCCESS = 'GET_ELECTRICITYDETAILS_SUCCESS';
export const GET_ELECTRICITYDETAILS_FAILURE = 'GET_ELECTRICITYDETAILS_FAILURE';