export const GET_CBHI_NID_DETAILS_REQUEST = 'GET_CBHI_NID_DETAILS_REQUEST';
export const GET_CBHI_NID_DETAILS_SUCCESS = 'GET_CBHI_NID_DETAILS_SUCCESS';
export const GET_CBHI_NID_DETAILS_FAILURE = 'GET_CBHI_NID_DETAILS_FAILURE'