export const GET_LTSSID_DETAILS_REQUEST = 'GET_LTSSID_DETAILS_REQUEST';
export const GET_LTSSID_DETAILS_SUCCESS = 'GET_LTSSID_DETAILS_SUCCESS';
export const GET_LTSSID_DETAILS_FAILURE = 'GET_LTSSID_DETAILS_FAILURE';