export const GET_RNIT_DETAILS_REQUEST = 'GET_RNIT_DETAILS_REQUEST';
export const GET_RNIT_DETAILS_SUCCESS = 'GET_RNIT_DETAILS_SUCCESS';
export const GET_RNIT_DETAILS_FAILURE = 'GET_RNIT_DETAILS_FAILURE';