export const GET_RIA_ORDER_DETAILS_REQUEST = 'GET_RIA_ORDER_DETAILS_REQUEST';
export const GET_RIA_ORDER_DETAILS_SUCCESS = 'GET_RIA_ORDER_DETAILS_SUCCESS';
export const GET_RIA_ORDER_DETAILS_FAILURE = 'GET_RIA_ORDER_DETAILS_FAILURE'