export const TOPUPMOBILEMONEY_REQUEST = 'TOPUPMOBILEMONEY_REQUEST';
export const TOPUPMOBILEMONEY_SUCCESS = 'TOPUPMOBILEMONEY_SUCCESS';
export const TOPUPMOBILEMONEY_FAILURE = 'TOPUPMOBILEMONEY_FAILURE';